FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y libgomp1 && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml .
COPY src/ src/
COPY ingest/ ingest/

RUN pip install -e ".[train,data,flows]"

CMD ["python", "src/f1_predictor/flows/pipeline_flow.py"]